### ISSUE TITLE
Is CRAN on the horizon?

### ISSUE THREAD

**Issue by Ljupch0** [moodymudskipper/safejoin#39]
Curious to know as I'm planning to use the safe joins in a production environment,

**Comment by moodymudskipper** [comment]
Not in the short term, in some places the code is a mess and I'd like to sort it out first, I think I should get to it though.
I was also thinking that dplyr would tackle this and didn't want to work for nothing, but they didn't and just released a major version so maybe I need to step back in.

I had stopped working on it because it worked for my purpose and I wasn't seeing much demand.

Any lurker seeing this please apply the emoji of your choice so I can see if there's demand and act accordingly.

If I do it, count a couple months to be safe.

**Comment by Ljupch0** [comment]
The conflict argument just saved my life. I can't believe that standard dplyr doesn't have it. In so many cases you're joining dfs with duplicate columns and you end up with the .x .y nightmare.

**Comment by moodymudskipper** [comment]
This {safejoin} package will never be on CRAN but {powerjoin} will be
